name: my_flutter_basic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.2

environment:
  sdk: '>=3.5.3 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 国际化
  flutter_localizations:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # 获取设备信息
  my_device_info:
    path: ./plugins/my_device_info

  # 图片处理
  my_gallery:
    path: ./plugins/my_gallery

  # 状态管理
  flutter_riverpod: ^2.6.1

  # svg
  flutter_svg: ^2.0.10+1

  # lottie
  lottie: ^3.3.1

  # 音频/音效
  audioplayers: ^6.4.0

  # 热更新
  shorebird_code_push: ^2.0.3

  # 网络请求
  dio: ^5.8.0+1

  # 缓存
  flutter_cache_manager: ^3.4.1

  # 加密
  encrypt: ^5.0.3

  # ws 模块
  web_socket_channel: ^3.0.2

  # 富文本
  flutter_html: ^3.0.0-beta.2

  # 下拉刷新
  pull_to_refresh: ^2.0.0

  # 滑动拓展
  flutter_slidable: ^4.0.0

  # 视频播放
  video_player: ^2.9.3

  # 播放器皮肤
  chewie: ^1.11.0

  # 压缩 / 解压缩
  archive: ^4.0.4

  # 深度链接
  app_links: ^6.4.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

analyzer:
  plugins:
    - custom_lint

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/dark/
    - assets/images/light/
    - assets/svg/
    - assets/svg/dark/
    - assets/svg/light/
    - assets/lottie/
    - assets/lottie/dark/
    - assets/lottie/light/
    - assets/audios/
    - assets/common/
    - shorebird.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
